// Code generated by Thrift Compiler (0.15.0). DO NOT EDIT.

package Upf

import (
	"bytes"
	"context"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

// Attributes:
//  - RxPktCount
//  - TxPktCount
type PortStats struct {
  RxPktCount int32 `thrift:"rxPktCount,1,required" db:"rxPktCount" json:"rxPktCount"`
  TxPktCount int32 `thrift:"txPktCount,2,required" db:"txPktCount" json:"txPktCount"`
}

func NewPortStats() *PortStats {
  return &PortStats{}
}


func (p *PortStats) GetRxPktCount() int32 {
  return p.RxPktCount
}

func (p *PortStats) GetTxPktCount() int32 {
  return p.TxPktCount
}
func (p *PortStats) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetRxPktCount bool = false;
  var issetTxPktCount bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
        issetRxPktCount = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
        issetTxPktCount = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetRxPktCount{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field RxPktCount is not set"));
  }
  if !issetTxPktCount{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field TxPktCount is not set"));
  }
  return nil
}

func (p *PortStats)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.RxPktCount = v
}
  return nil
}

func (p *PortStats)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.TxPktCount = v
}
  return nil
}

func (p *PortStats) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "PortStats"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *PortStats) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "rxPktCount", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:rxPktCount: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.RxPktCount)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.rxPktCount (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:rxPktCount: ", p), err) }
  return err
}

func (p *PortStats) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "txPktCount", thrift.I32, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:txPktCount: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.TxPktCount)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.txPktCount (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:txPktCount: ", p), err) }
  return err
}

func (p *PortStats) Equals(other *PortStats) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.RxPktCount != other.RxPktCount { return false }
  if p.TxPktCount != other.TxPktCount { return false }
  return true
}

func (p *PortStats) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("PortStats(%+v)", *p)
}

